# -*- coding: utf-8 -*-
"""extraerProgramacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaXzBoWNsgEGeaocngRvArlqMPDG73WE
"""

import pandas as pd
import json
import datetime

input_path = r"/content/programacion_26I.xlsx"
programacion = pd.read_excel(input_path, sheet_name='CB')

programacion['GRUPO'] = programacion['GRUPO'].astype(str).str.strip()

columnas_horarios = programacion.loc[:, 'L_I':'V_F'].columns
programacion[columnas_horarios] = (
    programacion[columnas_horarios]
    .fillna('00:00:00')
    .replace(r'^\s*$', '00:00:00', regex=True)
)

columnas_a_exportar = ['CLAVE', 'GRUPO', 'CM'] + list(columnas_horarios)
json_string = programacion[columnas_a_exportar].to_json(orient='records', force_ascii=False, indent=4)

with open ('programacion.json', 'w') as f:
  f.write(json_string)

class UEA:
	def __init__(self, clave):
		self.clave = clave
		self.registros = []

	def _normalizar_hora(self, v):
		if v is None:
			return "00:00:00"

		s = str(v).strip()

		if s.lower() in {"nan", "none", ""}:
			return "00:00:00"

		# "13:00" -> "13:00:00"
		if len(s) == 5 and s.count(":") == 1:
			return f"{s}:00"

		return s

	def _es_hora_cero(self, v):
		return self._normalizar_hora(v) == "00:00:00"

	def _dia_programado(self, bloque):
		return not (
			self._es_hora_cero(bloque["inicio"]) and
			self._es_hora_cero(bloque["fin"])
		)

	def _dias_agrupados(self, r):
		return {
			"L": {
				"inicio": self._normalizar_hora(r.get("L_I", "00:00:00")),
				"fin": self._normalizar_hora(r.get("L_F", "00:00:00"))
			},
			"M": {
				"inicio": self._normalizar_hora(r.get("M_I", "00:00:00")),
				"fin": self._normalizar_hora(r.get("M_F", "00:00:00"))
			},
			"Mi": {
				"inicio": self._normalizar_hora(r.get("Mi_I", "00:00:00")),
				"fin": self._normalizar_hora(r.get("Mi_F", "00:00:00"))
			},
			"J": {
				"inicio": self._normalizar_hora(r.get("J_I", "00:00:00")),
				"fin": self._normalizar_hora(r.get("J_F", "00:00:00"))
			},
			"V": {
				"inicio": self._normalizar_hora(r.get("V_I", "00:00:00")),
				"fin": self._normalizar_hora(r.get("V_F", "00:00:00"))
			}
		}

	def _quitar_dias_no_programados(self, dias):
		# Keep only days where at least one hour is not zero
		return {
			dia: bloque
			for dia, bloque in dias.items()
			if self._dia_programado(bloque)
		}

	def agregar_record(self, r):
		dias = self._dias_agrupados(r)
		dias = self._quitar_dias_no_programados(dias)  # <-- key fix

		# If after pruning days there is nothing scheduled, skip record entirely
		if not dias:
			return

		self.registros.append({
			"grupo": r["GRUPO"],
			"cupo": int(float(r["CM"])) if r["CM"] is not None else None,
			"dias": dias
		})

	def to_dict(self):
		return {
			"horarios_programados": self.registros
		}

records = json.loads(json_string)

objetos_por_clave = {}

for r in records:
	clave = r["CLAVE"]

	if clave not in objetos_por_clave:
		objetos_por_clave[clave] = UEA(clave)

	objetos_por_clave[clave].agregar_record(r)

# Remove CLAVEs with no programmed records
objetos_por_clave = {
	clave: uea
	for clave, uea in objetos_por_clave.items()
	if uea.registros
}

for clave, uea in objetos_por_clave.items():
	#print(clave, uea.to_dict())
 	pass

salida = {clave: uea.to_dict() for clave, uea in objetos_por_clave.items()}

with open('programacion_limpia.json', 'w', encoding='utf-8') as f:
	json.dump(salida, f, ensure_ascii=False, indent=4)