# -*- coding: utf-8 -*-
"""extraerGrupoNombre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PD5igHp8jAcNLYdJ-J784UfdeUKA_RPV
"""

import pandas as pd
import json

input_path = r"/content/programacion_26I.xlsx"
programacion = pd.read_excel(input_path, sheet_name='CB')

programacion['GRUPO'] = programacion['GRUPO'].astype(str).str.strip()
programacion = programacion.loc[:,'GRUPO']

unicos = programacion.drop_duplicates().tolist()

json_string = json.dumps(unicos)

with open('nombres_grupos.json', 'w', encoding='utf-8') as json_file:
    json_file.write(json_string)