# -*- coding: utf-8 -*-
"""obtenerClaveAreaUEAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9moK3e16-Xw_yBjQYXlNZvlhnjqoNw2
"""

import re
import pandas as pd
import numpy as np
import json
from collections import OrderedDict

input_file = r"/content/uea.xlsx"
source_sheet = "Ciencias Básicas"
output_file = r"/content/relacionUEA.json"

diccionarioPrefijos = {
    "1100": "TIM",
    "1111": "Física",
    "1112": "Matemáticas",
    "1113": "Química",
}

df = pd.read_excel(input_file, sheet_name=source_sheet)

key_col = "CLAVE" if "CLAVE" in df.columns else None
if key_col is None:
    print("No se encontró la columna CLAVE de las ueas.")

key_nombre = "UEA" if "UEA" in df.columns else None
if key_nombre is None:
    print("No se encontró la columna UEA de las ueas.")

uea_area = OrderedDict()
uea_nombre = OrderedDict()

for _, row in df.iterrows():
  if uea_nombre.get(row[key_col]) is None:
    uea_nombre[row[key_col]] = row[key_nombre]

  prefix = str(row[key_col])[0:4]
  if prefix in diccionarioPrefijos.keys():
    uea_area[row[key_col]] = diccionarioPrefijos[prefix]
  else:
    print("No se encontró el prefijo de la clave:", row[key_col])

json_uea = {}
for clave_uea, area_uea in uea_area.items():
  json_uea.update({clave_uea: {"nombre": uea_nombre[clave_uea], "area": area_uea}})
  #print(clave_uea, ':', uea_nombre[clave_uea].ljust(60), ':', area_uea)

#print(json.dumps(json_uea, indent=4, ensure_ascii=False))

with open(output_file, 'w') as json_file:
  json.dump(json_uea, json_file, indent=4, ensure_ascii=False)