# -*- coding: utf-8 -*-
"""obtenerGradoAreaProfesor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SMw_pkir_Bh_dBfYIybIDSL-3P0fxDKz
"""

import pandas as pd
import json

lista_profesores_path = r"/content/listaProfesores.xlsx"

lista_profesores = pd.read_excel(lista_profesores_path)
lista_profesores = lista_profesores.loc[:, 'NO. EC.':'ÁREA']
lista_profesores = lista_profesores.rename(columns={'NO. EC.':'numeroEconomico','ESTUDIOS':'grado', 'ÁREA':'area', 'NOMBRE(S)':'nombre'})
array_dict_profesores = lista_profesores.to_dict(orient='records')

profesores_json = {}
for profesor in lista_json:
  nombre = profesor['nombre'].rstrip()
  grado = profesor['grado'].rstrip()
  area = profesor['area'].rstrip()
  profesores_json.update({profesor['numeroEconomico']: {'nombre':nombre, 'grado':grado, 'area':area}})

json_output = r"/content/gradoYAreaProfesores.json"
with open(json_output, 'w') as json_file:
  json.dump(profesores_json, json_file, indent=4, ensure_ascii=False, )