# -*- coding: utf-8 -*-
"""parsearHorariosTrabajo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MEXVXUdniyeLv69AQQ2np7fqb5tglu_P
"""

import pandas as pd
import re
import json

input_path = r"data.xlsx"
horarios_excel = pd.read_excel(input_path, sheet_name="DEFINITIVOS")

horarios_excel = horarios_excel['HORARIO']
dias_keys = ['L-V', 'M-J', 'L-MI-V']
dias_re = re.compile(r"(L-MI-V|L-V|M-J)",re.IGNORECASE)
hora_re = re.compile(r"(\d{1,2})(?::(\d{2}))?\s*-\s*(\d{1,2})(?::(\d{2}))?")

def norm_time(h, m):
  h = int(h)
  m = int(m) if m else 0
  return f"{h:02d}:{m:02d}"

horarios = {k: set() for k in dias_keys}

for cell in horarios_excel:
	if pd.isna(cell):
		continue

	row = str(cell).upper()
	row = row.replace(" ", "").replace("*", "")
	row = row.replace("HRS", "").replace("HR", "")
	row = row.replace("–", "-").replace("—", "-")

	if not row:
		continue

	day_marks = list(dias_re.finditer(row))

	# Si una fila no trae día pero trae horario, opcionalmente lo metemos en L-V
	if not day_marks:
		for m in hora_re.finditer(row):
			horarios["L-V"].add(f"{norm_time(m.group(1), m.group(2))}-{norm_time(m.group(3), m.group(4))}")
		continue

	# Para cada bloque (día ... hasta antes del siguiente día), extrae sus horarios
	for i, dm in enumerate(day_marks):
		dia = dm.group(1).upper()
		start = dm.end()
		end = day_marks[i + 1].start() if i + 1 < len(day_marks) else len(row)
		segment = row[start:end]

		for m in hora_re.finditer(segment):
			horarios[dia].add(f"{norm_time(m.group(1), m.group(2))}-{norm_time(m.group(3), m.group(4))}")

# JSON no soporta sets -> convertir a listas (ordenadas para que sea estable)
horarios_json = {k: sorted(v) for k, v in horarios.items()}
print(json.dumps(horarios_json, ensure_ascii=False, indent=2))

output_path = r"horarios_contratacion.json"
with open(output_path, "w") as f:
	json.dump(horarios_json, f, ensure_ascii=False, indent=4)

import pandas as pd
import re
import json

input_path = r"/content/data.xlsx"  # o r"data.xlsx"
df = pd.read_excel(input_path, sheet_name="DEFINITIVOS")

dias_keys = ["L-V", "M-J", "L-MI-V"]

# Pon primero el más largo para evitar matches parciales
dias_re = re.compile(r"(L-MI-V|L-V|M-J)", re.IGNORECASE)

# Rangos tipo 7:00-10:00, 10-18, 11:30-19:30, etc.
hora_re = re.compile(r"(\d{1,2})(?::(\d{2}))?\s*-\s*(\d{1,2})(?::(\d{2}))?")

def norm_time(h, m):
	h = int(h)
	m = int(m) if m else 0
	return f"{h:02d}:{m:02d}"

# DÍA -> HORARIO -> {"numerosEconomicos": set()}
horarios = {k: {} for k in dias_keys}

for _, r in df[["NO. EC.", "HORARIO"]].iterrows():
	noec = r["NO. EC."]
	hor = r["HORARIO"]

	if pd.isna(noec) or pd.isna(hor):
		continue

	try:
		noec = int(noec)
	except Exception:
		continue

	s = str(hor).upper()
	s = s.replace("*", "")
	s = s.replace("HRS", "").replace("HR", "")
	s = s.replace("–", "-").replace("—", "-")

	day_marks = list(dias_re.finditer(s))
	if not day_marks:
		continue  # o mete default si quieres (ej. L-V)

	# Para cada bloque: (DÍA) ... hasta antes del siguiente (DÍA)
	for i, dm in enumerate(day_marks):
		dia = dm.group(1).upper()
		start = dm.end()
		end = day_marks[i + 1].start() if i + 1 < len(day_marks) else len(s)
		segment = s[start:end]

		for m in hora_re.finditer(segment):
			rango = f"{norm_time(m.group(1), m.group(2))}-{norm_time(m.group(3), m.group(4))}"

			horarios[dia].setdefault(rango, {"numerosEconomicos": set()})
			horarios[dia][rango]["numerosEconomicos"].add(noec)

# JSON no soporta set -> convertir a listas ordenadas
horarios_json = {
	dia: {
		rango: {"numerosEconomicos": sorted(list(info["numerosEconomicos"]))}
		for rango, info in horarios[dia].items()
	}
	for dia in dias_keys
}

print(json.dumps(horarios_json, ensure_ascii=False, indent=4))

output_path = r"/content/horarios_contratacion_profesores.json"

with open(output_path, "w") as f:
	json.dump(horarios_json, f, ensure_ascii=False, indent=4)

from google.colab import drive
drive.mount('/content/drive')