-- MySQL Script generated by MySQL Workbench
-- Mon Oct 20 15:25:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbdocenciacb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbdocenciacb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbdocenciacb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
-- -----------------------------------------------------
-- Schema dbappcb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbappcb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbappcb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `dbdocenciacb` ;

-- -----------------------------------------------------
-- Table `dbdocenciacb`.`AreaUEA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`AreaUEA` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`AreaUEA` (
  `idAreaUEA` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idAreaUEA`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Categoria` (
  `idCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nomCategoria` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`UEA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`UEA` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`UEA` (
  `idUEA` INT(11) NOT NULL AUTO_INCREMENT,
  `claveUEA` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(125) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `idArea` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUEA`),
  UNIQUE INDEX `idUEA` (`idUEA` ASC) VISIBLE,
  INDEX `FK_area` (`idArea` ASC) VISIBLE,
  CONSTRAINT `FK_area`
    FOREIGN KEY (`idArea`)
    REFERENCES `dbdocenciacb`.`AreaUEA` (`idAreaUEA`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Grupo` (
  `idGrupo` INT(11) NOT NULL AUTO_INCREMENT,
  `claveGrupo` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `cupo` INT(11) NULL DEFAULT NULL,
  `idUEA` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupo`),
  INDEX `FK_ueag` (`idUEA` ASC) VISIBLE,
  CONSTRAINT `FK_ueag`
    FOREIGN KEY (`idUEA`)
    REFERENCES `dbdocenciacb`.`UEA` (`idUEA`))
ENGINE = InnoDB
AUTO_INCREMENT = 3754
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Horario` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Horario` (
  `idHorario` INT(11) NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `horaInicio` TIME NULL DEFAULT NULL,
  `horaFin` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB
AUTO_INCREMENT = 230
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Grupo_Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Grupo_Horario` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Grupo_Horario` (
  `idGrupoHor` INT(11) NOT NULL AUTO_INCREMENT,
  `idHorario` INT(11) NULL DEFAULT NULL,
  `idGrupo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupoHor`),
  INDEX `FK_grupo` (`idGrupo` ASC) VISIBLE,
  INDEX `FK_diag` (`idHorario` ASC) VISIBLE,
  CONSTRAINT `FK_diag`
    FOREIGN KEY (`idHorario`)
    REFERENCES `dbdocenciacb`.`Horario` (`idHorario`),
  CONSTRAINT `FK_grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `dbdocenciacb`.`Grupo` (`idGrupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 1981
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Integrante` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Integrante` (
  `idIntegrante` INT(11) NOT NULL AUTO_INCREMENT,
  `saludo` VARCHAR(70) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIntegrante`))
ENGINE = InnoDB
AUTO_INCREMENT = 1254
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`IntegranteHasCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`IntegranteHasCategoria` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`IntegranteHasCategoria` (
  `idIntegranteHasCategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `idIntegrante` INT(11) NOT NULL,
  `idCategoria` INT(11) NOT NULL,
  PRIMARY KEY (`idIntegranteHasCategoria`),
  INDEX `idIntegrante_idx` (`idIntegrante` ASC) VISIBLE,
  INDEX `FK_idCategoria_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `FK_idCategoria`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbdocenciacb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idIntegrante`
    FOREIGN KEY (`idIntegrante`)
    REFERENCES `dbdocenciacb`.`Integrante` (`idIntegrante`))
ENGINE = InnoDB
AUTO_INCREMENT = 1252
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Profesor` (
  `idProf` INT(11) NOT NULL AUTO_INCREMENT,
  `noEconomico` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(125) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `correo_uam` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `correo_personal` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idProf`),
  UNIQUE INDEX `idProf` (`idProf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 130
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`Programacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`Programacion` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`Programacion` (
  `idProg` INT(11) NOT NULL AUTO_INCREMENT,
  `idGrupo` INT(11) NULL DEFAULT NULL,
  `idProf` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idProg`),
  INDEX `FK_profe` (`idProf` ASC) VISIBLE,
  INDEX `FK_grup` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `FK_grup`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `dbdocenciacb`.`Grupo` (`idGrupo`),
  CONSTRAINT `FK_profe`
    FOREIGN KEY (`idProf`)
    REFERENCES `dbdocenciacb`.`Profesor` (`idProf`))
ENGINE = InnoDB
AUTO_INCREMENT = 222
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`solicitud_horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`solicitud_horario` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`solicitud_horario` (
  `idSolHor` INT(11) NOT NULL AUTO_INCREMENT,
  `idProf` INT(11) NULL DEFAULT NULL,
  `idHorario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idSolHor`),
  INDEX `FKidProf` (`idProf` ASC) VISIBLE,
  INDEX `FK_diap` (`idHorario` ASC) VISIBLE,
  CONSTRAINT `FK_diap`
    FOREIGN KEY (`idHorario`)
    REFERENCES `dbdocenciacb`.`Horario` (`idHorario`),
  CONSTRAINT `FKidProf`
    FOREIGN KEY (`idProf`)
    REFERENCES `dbdocenciacb`.`Profesor` (`idProf`))
ENGINE = InnoDB
AUTO_INCREMENT = 926
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`solicitud_profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`solicitud_profesor` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`solicitud_profesor` (
  `idSolProf` INT(11) NOT NULL AUTO_INCREMENT,
  `idProf` INT(11) NULL DEFAULT NULL,
  `noGrupos` INT(11) NULL DEFAULT NULL,
  `observaciones` VARCHAR(955) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idSolProf`),
  INDEX `FK_idProfe` (`idProf` ASC) VISIBLE,
  CONSTRAINT `FK_idProfe`
    FOREIGN KEY (`idProf`)
    REFERENCES `dbdocenciacb`.`Profesor` (`idProf`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`solicitud_uea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`solicitud_uea` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`solicitud_uea` (
  `idSol_uea` INT(11) NOT NULL AUTO_INCREMENT,
  `idProf` INT(11) NULL DEFAULT NULL,
  `idUEA` INT(11) NULL DEFAULT NULL,
  `prioridad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idSol_uea`),
  INDEX `FK_prof` (`idProf` ASC) VISIBLE,
  INDEX `FK_uea` (`idUEA` ASC) VISIBLE,
  CONSTRAINT `FK_prof`
    FOREIGN KEY (`idProf`)
    REFERENCES `dbdocenciacb`.`Profesor` (`idProf`),
  CONSTRAINT `FK_uea`
    FOREIGN KEY (`idUEA`)
    REFERENCES `dbdocenciacb`.`UEA` (`idUEA`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`trimestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`trimestre` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`trimestre` (
  `idTrimestre` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaLim` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idTrimestre`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `dbdocenciacb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbdocenciacb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(125) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `pwd` VARCHAR(125) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

USE `dbappcb` ;

-- -----------------------------------------------------
-- Table `dbappcb`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`area` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`area` (
  `idArea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`uea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`uea` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`uea` (
  `idUEA` INT NOT NULL AUTO_INCREMENT,
  `area_idArea` INT NOT NULL,
  `claveUEA` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(125) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idUEA`),
  UNIQUE INDEX `idUEA` (`idUEA` ASC) VISIBLE,
  INDEX `fk_UEA_area1_idx` (`area_idArea` ASC) VISIBLE,
  CONSTRAINT `fk_UEA_area1`
    FOREIGN KEY (`area_idArea`)
    REFERENCES `dbappcb`.`area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`trimestreperiodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`trimestreperiodo` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`trimestreperiodo` (
  `idTrimestrePeriodo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `sigla` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idTrimestrePeriodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`trimestre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`trimestre` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`trimestre` (
  `idTrimestre` INT NOT NULL AUTO_INCREMENT,
  `año` INT NOT NULL,
  `trimestreperiodo_idTrimestrePeriodo` INT NOT NULL,
  `fechaLimite` DATE NOT NULL,
  PRIMARY KEY (`idTrimestre`),
  INDEX `fk_trimestre_trimestreperiodo1_idx` (`trimestreperiodo_idTrimestrePeriodo` ASC) VISIBLE,
  CONSTRAINT `fk_trimestre_trimestreperiodo1`
    FOREIGN KEY (`trimestreperiodo_idTrimestrePeriodo`)
    REFERENCES `dbappcb`.`trimestreperiodo` (`idTrimestrePeriodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `dbappcb`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`grupo` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `trimestre_idTrimestre` INT NOT NULL,
  `uea_idUEA` INT NOT NULL,
  `claveGrupo` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `cupo` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idGrupo`, `trimestre_idTrimestre`),
  INDEX `fk_Grupo_UEA1_idx` (`uea_idUEA` ASC) VISIBLE,
  INDEX `fk_grupo_trimestre1_idx` (`trimestre_idTrimestre` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_UEA1`
    FOREIGN KEY (`uea_idUEA`)
    REFERENCES `dbappcb`.`uea` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_trimestre1`
    FOREIGN KEY (`trimestre_idTrimestre`)
    REFERENCES `dbappcb`.`trimestre` (`idTrimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3754
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`horario` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(25) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB
AUTO_INCREMENT = 230
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesor` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesor` (
  `idProfesor` INT NOT NULL AUTO_INCREMENT,
  `numeroEconomico` INT NOT NULL,
  `nombre` VARCHAR(125) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `gradoEstudios` VARCHAR(80) NOT NULL,
  `celular` INT NULL,
  `correo_uam` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  `correo_personal` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  PRIMARY KEY (`idProfesor`),
  UNIQUE INDEX `idProf` (`idProfesor` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 130
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesorpreferencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesorpreferencias` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesorpreferencias` (
  `idProfesorPreferencias` INT NOT NULL AUTO_INCREMENT,
  `profesor_idProfesor` INT NOT NULL,
  `trimestre_idTrimestre` INT NOT NULL,
  `noGrupos` INT NULL DEFAULT NULL,
  `observaciones` VARCHAR(955) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`idProfesorPreferencias`),
  INDEX `fk_profesorPreferencia_trimestre1_idx` (`trimestre_idTrimestre` ASC) VISIBLE,
  INDEX `fk_profesorPreferencia_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesorPreferencia_trimestre1`
    FOREIGN KEY (`trimestre_idTrimestre`)
    REFERENCES `dbappcb`.`trimestre` (`idTrimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesorPreferencia_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbappcb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `contraseña` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `intento` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`funcion` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`funcion` (
  `idFuncion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idFuncion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`usuario_has_funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`usuario_has_funcion` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`usuario_has_funcion` (
  `usuario_idUsuario` INT NOT NULL,
  `funcion_idFuncion` INT NOT NULL,
  PRIMARY KEY (`usuario_idUsuario`, `funcion_idFuncion`),
  INDEX `fk_usuario_has_funcion_funcion1_idx` (`funcion_idFuncion` ASC) VISIBLE,
  INDEX `fk_usuario_has_funcion_usuario1_idx` (`usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_funcion_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `dbappcb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_funcion_funcion1`
    FOREIGN KEY (`funcion_idFuncion`)
    REFERENCES `dbappcb`.`funcion` (`idFuncion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesortipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesortipo` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesortipo` (
  `idProfesorTipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idProfesorTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesoremergencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesoremergencia` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesoremergencia` (
  `idProfesorEmergencia` INT NOT NULL AUTO_INCREMENT,
  `profesor_idProfesor` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `parentesco` VARCHAR(255) NOT NULL,
  `celular` INT NULL,
  PRIMARY KEY (`idProfesorEmergencia`, `profesor_idProfesor`),
  INDEX `fk_profesoremergencia_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesoremergencia_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`lugar` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`lugar` (
  `idLugar` INT NOT NULL AUTO_INCREMENT,
  `edificio` VARCHAR(45) NOT NULL,
  `piso` INT NOT NULL,
  `cubiculo` VARCHAR(45) NULL,
  `nombre` VARCHAR(150) NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`idLugar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesordisposicion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesordisposicion` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesordisposicion` (
  `idProfesorDisposicion` INT NOT NULL AUTO_INCREMENT,
  `trimestre_idTrimestre` INT NOT NULL,
  `profesor_idProfesor` INT NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`idProfesorDisposicion`, `trimestre_idTrimestre`),
  INDEX `fk_profesordisposicion_trimestre1_idx` (`trimestre_idTrimestre` ASC) VISIBLE,
  INDEX `fk_profesordisposicion_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesordisposicion_trimestre1`
    FOREIGN KEY (`trimestre_idTrimestre`)
    REFERENCES `dbappcb`.`trimestre` (`idTrimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesordisposicion_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesor_has_lugar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesor_has_lugar` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesor_has_lugar` (
  `profesor_idProfesor` INT NOT NULL,
  `lugar_idLugar` INT NOT NULL,
  PRIMARY KEY (`profesor_idProfesor`, `lugar_idLugar`),
  INDEX `fk_profesor_has_lugar_lugar1_idx` (`lugar_idLugar` ASC) VISIBLE,
  INDEX `fk_profesor_has_lugar_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_has_lugar_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_has_lugar_lugar1`
    FOREIGN KEY (`lugar_idLugar`)
    REFERENCES `dbappcb`.`lugar` (`idLugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesorcontrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesorcontrato` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesorcontrato` (
  `idProfesorContrato` INT NOT NULL AUTO_INCREMENT,
  `profesor_idProfesor` INT NOT NULL,
  `profesortipo_idProfesorTipo` INT NOT NULL,
  `horaInicio` TIME NULL,
  `horaFin` TIME NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idProfesorContrato`, `profesor_idProfesor`),
  INDEX `fk_profesorcontrato_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_profesorcontrato_profesortipo1_idx` (`profesortipo_idProfesorTipo` ASC) VISIBLE,
  CONSTRAINT `fk_profesorcontrato_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesorcontrato_profesortipo1`
    FOREIGN KEY (`profesortipo_idProfesorTipo`)
    REFERENCES `dbappcb`.`profesortipo` (`idProfesorTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesor_has_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesor_has_area` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesor_has_area` (
  `profesor_idProfesor` INT NOT NULL,
  `area_idArea` INT NOT NULL,
  `descripcionInformal` VARCHAR(255) NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`profesor_idProfesor`, `area_idArea`),
  INDEX `fk_profesor_has_area_area1_idx` (`area_idArea` ASC) VISIBLE,
  INDEX `fk_profesor_has_area_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_has_area_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesor_has_area_area1`
    FOREIGN KEY (`area_idArea`)
    REFERENCES `dbappcb`.`area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesorcontrato_has_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesorcontrato_has_area` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesorcontrato_has_area` (
  `profesorcontrato_idProfesorContrato` INT NOT NULL,
  `profesorcontrato_profesor_idProf` INT NOT NULL,
  `area_idArea` INT NOT NULL,
  PRIMARY KEY (`profesorcontrato_idProfesorContrato`, `profesorcontrato_profesor_idProf`, `area_idArea`),
  INDEX `fk_profesorcontrato_has_area_area1_idx` (`area_idArea` ASC) VISIBLE,
  INDEX `fk_profesorcontrato_has_area_profesorcontrato1_idx` (`profesorcontrato_idProfesorContrato` ASC, `profesorcontrato_profesor_idProf` ASC) VISIBLE,
  CONSTRAINT `fk_profesorcontrato_has_area_profesorcontrato1`
    FOREIGN KEY (`profesorcontrato_idProfesorContrato` , `profesorcontrato_profesor_idProf`)
    REFERENCES `dbappcb`.`profesorcontrato` (`idProfesorContrato` , `profesor_idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesorcontrato_has_area_area1`
    FOREIGN KEY (`area_idArea`)
    REFERENCES `dbappcb`.`area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`prestamo` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`prestamo` (
  `idPrestamo` INT NOT NULL AUTO_INCREMENT,
  `profesor_idProfesor` INT NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `dia` DATE NOT NULL,
  `notas` VARCHAR(255) NULL,
  PRIMARY KEY (`idPrestamo`),
  INDEX `fk_prestamo_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`grupo_has_horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`grupo_has_horario` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`grupo_has_horario` (
  `grupo_idGrupo` INT NOT NULL,
  `horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`grupo_idGrupo`, `horario_idHorario`),
  INDEX `fk_Grupo_has_Horario_Horario1_idx` (`horario_idHorario` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Horario_Grupo1_idx` (`grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Horario_Grupo1`
    FOREIGN KEY (`grupo_idGrupo`)
    REFERENCES `dbappcb`.`grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Horario_Horario1`
    FOREIGN KEY (`horario_idHorario`)
    REFERENCES `dbappcb`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesorpreferencia_has_uea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesorpreferencia_has_uea` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesorpreferencia_has_uea` (
  `profesorPreferencia_idProfesorPreferencias` INT NOT NULL,
  `uea_idUEA` INT NOT NULL,
  `prioridad` INT NOT NULL,
  PRIMARY KEY (`profesorPreferencia_idProfesorPreferencias`, `uea_idUEA`),
  INDEX `fk_profesorPreferencia_has_UEA_UEA1_idx` (`uea_idUEA` ASC) VISIBLE,
  INDEX `fk_profesorPreferencia_has_UEA_profesorPreferencia1_idx` (`profesorPreferencia_idProfesorPreferencias` ASC) VISIBLE,
  CONSTRAINT `fk_profesorPreferencia_has_UEA_profesorPreferencia1`
    FOREIGN KEY (`profesorPreferencia_idProfesorPreferencias`)
    REFERENCES `dbappcb`.`profesorpreferencias` (`idProfesorPreferencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesorPreferencia_has_UEA_UEA1`
    FOREIGN KEY (`uea_idUEA`)
    REFERENCES `dbappcb`.`uea` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesorpreferencia_has_horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesorpreferencia_has_horario` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesorpreferencia_has_horario` (
  `horario_idHorario` INT NOT NULL,
  `profesorPreferencia_idProfesorPreferencias` INT NOT NULL,
  PRIMARY KEY (`horario_idHorario`, `profesorPreferencia_idProfesorPreferencias`),
  INDEX `fk_Horario_has_profesorPreferencia_profesorPreferencia1_idx` (`profesorPreferencia_idProfesorPreferencias` ASC) VISIBLE,
  INDEX `fk_Horario_has_profesorPreferencia_Horario1_idx` (`horario_idHorario` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_has_profesorPreferencia_Horario1`
    FOREIGN KEY (`horario_idHorario`)
    REFERENCES `dbappcb`.`horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_has_profesorPreferencia_profesorPreferencia1`
    FOREIGN KEY (`profesorPreferencia_idProfesorPreferencias`)
    REFERENCES `dbappcb`.`profesorpreferencias` (`idProfesorPreferencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbappcb`.`areaacademica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`areaacademica` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`areaacademica` (
  `idAreaAcademica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAreaAcademica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`grupotematico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`grupotematico` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`grupotematico` (
  `idGrupoTematico` INT NOT NULL AUTO_INCREMENT,
  `nombreGrupo` VARCHAR(120) NOT NULL,
  `puesto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGrupoTematico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`areaacademica_has_profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`areaacademica_has_profesor` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`areaacademica_has_profesor` (
  `areaAcademica_idAreaAcademica` INT NOT NULL,
  `profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`areaAcademica_idAreaAcademica`, `profesor_idProfesor`),
  INDEX `fk_areaAcademica_has_profesor_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_areaAcademica_has_profesor_areaAcademica1_idx` (`areaAcademica_idAreaAcademica` ASC) VISIBLE,
  CONSTRAINT `fk_areaAcademica_has_profesor_areaAcademica1`
    FOREIGN KEY (`areaAcademica_idAreaAcademica`)
    REFERENCES `dbappcb`.`areaacademica` (`idAreaAcademica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_areaAcademica_has_profesor_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`grupotematico_has_profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`grupotematico_has_profesor` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`grupotematico_has_profesor` (
  `grupoTematico_idGrupoTematico` INT NOT NULL,
  `profesor_idProfesor` INT NOT NULL,
  PRIMARY KEY (`grupoTematico_idGrupoTematico`, `profesor_idProfesor`),
  INDEX `fk_grupoTematico_has_profesor_profesor1_idx` (`profesor_idProfesor` ASC) VISIBLE,
  INDEX `fk_grupoTematico_has_profesor_grupoTematico1_idx` (`grupoTematico_idGrupoTematico` ASC) VISIBLE,
  CONSTRAINT `fk_grupoTematico_has_profesor_grupoTematico1`
    FOREIGN KEY (`grupoTematico_idGrupoTematico`)
    REFERENCES `dbappcb`.`grupotematico` (`idGrupoTematico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupoTematico_has_profesor_profesor1`
    FOREIGN KEY (`profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`material` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`material` (
  `idMaterial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`prestamo_has_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`prestamo_has_material` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`prestamo_has_material` (
  `prestamo_idPrestamo` INT NOT NULL,
  `material_idMaterial` INT NOT NULL,
  PRIMARY KEY (`prestamo_idPrestamo`, `material_idMaterial`),
  INDEX `fk_prestamo_has_material_material1_idx` (`material_idMaterial` ASC) VISIBLE,
  INDEX `fk_prestamo_has_material_prestamo1_idx` (`prestamo_idPrestamo` ASC) VISIBLE,
  CONSTRAINT `fk_prestamo_has_material_prestamo1`
    FOREIGN KEY (`prestamo_idPrestamo`)
    REFERENCES `dbappcb`.`prestamo` (`idPrestamo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prestamo_has_material_material1`
    FOREIGN KEY (`material_idMaterial`)
    REFERENCES `dbappcb`.`material` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`profesorcontrato_has_uea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`profesorcontrato_has_uea` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`profesorcontrato_has_uea` (
  `profesorcontrato_idProfesorContrato` INT NOT NULL,
  `profesorcontrato_profesor_idProfesor` INT(11) NOT NULL,
  `uea_idUEA` INT NOT NULL,
  PRIMARY KEY (`profesorcontrato_idProfesorContrato`, `profesorcontrato_profesor_idProfesor`, `uea_idUEA`),
  INDEX `fk_profesorcontrato_has_uea_uea1_idx` (`uea_idUEA` ASC) VISIBLE,
  INDEX `fk_profesorcontrato_has_uea_profesorcontrato1_idx` (`profesorcontrato_idProfesorContrato` ASC, `profesorcontrato_profesor_idProfesor` ASC) VISIBLE,
  CONSTRAINT `fk_profesorcontrato_has_uea_profesorcontrato1`
    FOREIGN KEY (`profesorcontrato_idProfesorContrato` , `profesorcontrato_profesor_idProfesor`)
    REFERENCES `dbappcb`.`profesorcontrato` (`idProfesorContrato` , `profesor_idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profesorcontrato_has_uea_uea1`
    FOREIGN KEY (`uea_idUEA`)
    REFERENCES `dbappcb`.`uea` (`idUEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbappcb`.`programacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbappcb`.`programacion` ;

CREATE TABLE IF NOT EXISTS `dbappcb`.`programacion` (
  `grupo_trimestre_idTrimestre` INT NOT NULL,
  `grupo_idGrupo` INT NOT NULL,
  `profesordisposicion_idProfesorDisposicion` INT NOT NULL,
  PRIMARY KEY (`grupo_trimestre_idTrimestre`, `grupo_idGrupo`, `profesordisposicion_idProfesorDisposicion`),
  INDEX `fk_profesor_has_grupo_grupo1_idx` (`grupo_idGrupo` ASC, `grupo_trimestre_idTrimestre` ASC) VISIBLE,
  INDEX `fk_programacion_profesordisposicion1_idx` (`profesordisposicion_idProfesorDisposicion` ASC) VISIBLE,
  CONSTRAINT `fk_profesor_has_grupo_grupo1`
    FOREIGN KEY (`grupo_idGrupo` , `grupo_trimestre_idTrimestre`)
    REFERENCES `dbappcb`.`grupo` (`idGrupo` , `trimestre_idTrimestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programacion_profesordisposicion1`
    FOREIGN KEY (`profesordisposicion_idProfesorDisposicion`)
    REFERENCES `dbappcb`.`profesordisposicion` (`idProfesorDisposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `dbdocenciacb` ;

-- -----------------------------------------------------
-- Placeholder table for view `dbdocenciacb`.`horario_uea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`horario_uea` (`idGrupo` INT, `claveGrupo` INT, `idHorario` INT, `dia` INT, `horaInicio` INT, `horaFin` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dbdocenciacb`.`programacion_actual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdocenciacb`.`programacion_actual` (`idProf` INT, `idUEA` INT, `nombre` INT, `idGrupo` INT, `idHorario` INT);

-- -----------------------------------------------------
-- procedure CREA_TABLA_HORARIO_UEA
-- -----------------------------------------------------

USE `dbdocenciacb`;
DROP procedure IF EXISTS `dbdocenciacb`.`CREA_TABLA_HORARIO_UEA`;

DELIMITER $$
USE `dbdocenciacb`$$
CREATE DEFINER=`usrdoccb`@`%` PROCEDURE `CREA_TABLA_HORARIO_UEA`(_idUEA int)
BEGIN
		DROP TABLE IF EXISTS horario_uea;
		CREATE TABLE horario_uea 
		SELECT Grupo.idGrupo,Grupo.claveGrupo,Horario.idHorario,Horario.dia,Horario.horaInicio,Horario.horaFin 
        FROM (((Grupo INNER JOIN UEA ON Grupo.idUEA=UEA.idUEA) 
        INNER JOIN Grupo_Horario ON Grupo.idGrupo=Grupo_Horario.idGrupo)
        INNER JOIN Horario ON Grupo_Horario.idHorario=Horario.idHorario)
        WHERE UEA.idUEA=_idUEA;
	END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERTA_GRUPO
-- -----------------------------------------------------

USE `dbdocenciacb`;
DROP procedure IF EXISTS `dbdocenciacb`.`INSERTA_GRUPO`;

DELIMITER $$
USE `dbdocenciacb`$$
CREATE DEFINER=`usrdoccb`@`%` PROCEDURE `INSERTA_GRUPO`(_claveUEA int,_grupo varchar(25),_cupo int)
BEGIN
		DECLARE X INT;
		SELECT idUEA INTO X FROM UEA WHERE UEA.claveUEA = _claveUEA;
        INSERT INTO Grupo VALUES (NULL,_grupo,_cupo,X);
	END$$

DELIMITER ;

